services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: _9rGfw6nM-Cbv_Twnywx
      MYSQL_DATABASE: dev
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
