spring:
  cloud:
    gateway:
      routes:
        - id: rest-route
          uri: ${REST_ROUTE_URI:http://localhost:8080}
          predicates:
            - Path=/rest/**
          filters:
            - StripPrefix=1
  application:
    name: bachelor-rest-api
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:test_db}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL:create}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}
